# Задача на ошибки в корутинах

### Условие:

```
fun main() {
    runBlocking {
        println("Weather forecast")
        println(getWeatherReport())
        println("Have a good day!")
    }
}
```

```
suspend fun getWeatherReport() = coroutineScope {
    val forecast = async { getForecast() }
    val temperature = async { getTemperature() }
    
    delay(200)
    
    temperature.cancel()
    "${forecast.await()}"
//  "${forecast.await()} ${temperature.await()} а здесь что произойдет?"
}
```

```
suspend fun getForecast(): String {
    delay(1000)
    return "Sunny"
}
```

```
suspend fun getTemperature(): String {
    delay(500)
    throw AssertionError("Temperature is invalid")
    return "30 graduses"
}
```

### Задача 1

Опишите работу программы

### Ответ:

1. `runBlocking()` блокирует текущий поток
2. В консоль печатется: `Weather forecast`
3. Вызовется `getWeatherReport()`
4. Создастся новый скоуп с `ScopeJob` как родительской `Job`
5. Запустятся две корутины билдерами `async()`
6. Выполнение кода `coroutineScope` будет приостановлено на 200мс
7. `getForecast()` начнет выполнение блока кода и будет приостановлено на 1 секунду
8. `getTemperature()` начнет выполнение блока кода и приостановится в функции `delay` на 500 мс
9. Заканчивается `delay()` в `coroutineScope()`
10. Вызовется отмена корутины `temperature`
11. `coroutineScope()` подписывается на результат корутины `forecast()`
12. `getForecast()` -> `delay()` -> `suspendCancelableCoroutine()` бросает `CancellationException`
13. Отменяется корутина `temperature`
14. Заканчивается `delay()` у `getForecast()`
15. `getWeatherReport()` возвращает строку
16. В консоль печатется: `Sunny`
17. В консоль печатется: `Have a good day!`
18. Процесс завершается

### Задача 2

Изменится ли результат работы программы, если значение `delay` в `getTemperature()` установить 100

### Ответ:

Меняется порядок начиная с 12 пункта

12. Бросается исключение в getForecast
13. Отменяется корутина temperature и передается ошибка родителю coroutineScope, он сообщает async
    что может обработать ошибку
14. Ошибка пробрасывается в место вызова suspend fun coroutineScope
15. Глобальный обработчик пишет в консоль стек трейс ошибки
16. Процесс завершается с ошибкой AssertionError

### Задача 3

Изменится ли результат работы программы если

`"${forecast.await()}"`

Заменить на

`"${forecast.await()} ${temperature.await()}`

### Ответ:

Меняется порядок начиная с 11 пункта

11. `coroutineScope()` подписывается на результат корутин `forecast()`, `temperature`
13. Отменяется корутина `temperature`
14. suspend fun `await()` бросает `JobCancellationException`
15. Ошибка пробрасывается в место вызова suspend fun `coroutineScope`
16. Глобальный обработчик пишет в консоль стек трейс ошибки
17. Процесс завершается с ошибкой `JobCancellationException: DeferredCoroutine was cancelled`
